"""Add columns to Football_Teams table

Revision ID: 01e83d09bfe2
Revises: 41b26df8c840
Create Date: 2023-04-15 17:51:02.425477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01e83d09bfe2'
down_revision = '41b26df8c840'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('football__teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_and_time_of_game', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('current_score', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('football__teams', schema=None) as batch_op:
        batch_op.drop_column('current_score')
        batch_op.drop_column('date_and_time_of_game')

    # ### end Alembic commands ###
