"""Add Waiver_Info table and add DropComplete form

Revision ID: 11106d4d5441
Revises: f9f16aea7f11
Create Date: 2023-04-30 15:46:26.025227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11106d4d5441'
down_revision = 'f9f16aea7f11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waiver__info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('league', sa.Integer(), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'league', ['league'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('league_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waiver__info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('league_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('league')

    # ### end Alembic commands ###
