"""Add opponent_p5 to Football_Teams table

Revision ID: 1b29381764b2
Revises: b99f02befeb1
Create Date: 2024-08-11 07:59:36.676613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b29381764b2'
down_revision = 'b99f02befeb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('football__teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('opponent_p5', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('football__teams', schema=None) as batch_op:
        batch_op.drop_column('opponent_p5')

    # ### end Alembic commands ###
