"""add league_password to LeagueForm, JoinLeagueForm, and League

Revision ID: 27437bbcea07
Revises: 5a0e02fb7f6e
Create Date: 2023-03-22 20:38:53.968764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27437bbcea07'
down_revision = '5a0e02fb7f6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('league', schema=None) as batch_op:
        batch_op.add_column(sa.Column('league_password', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('league', schema=None) as batch_op:
        batch_op.drop_column('league_password')

    # ### end Alembic commands ###
