"""test

Revision ID: 2fa0f3a5c885
Revises: 99c8148c9c73
Create Date: 2023-07-08 11:56:38.827637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fa0f3a5c885'
down_revision = '99c8148c9c73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('league', schema=None) as batch_op:
        batch_op.add_column(sa.Column('waivers_already_executed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('league', schema=None) as batch_op:
        batch_op.drop_column('waivers_already_executed')

    # ### end Alembic commands ###
