"""Lock accounts due to too many unsuccessful login attempts

Revision ID: 32e023b1da7f
Revises: 2fa0f3a5c885
Create Date: 2023-07-16 14:31:38.543704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32e023b1da7f'
down_revision = '2fa0f3a5c885'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('failed_login_attempts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('locked_account', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('locked_account')
        batch_op.drop_column('failed_login_attempts')

    # ### end Alembic commands ###
