"""remoe league_id from league_members

Revision ID: 3620de4c5783
Revises: e43454b58e77
Create Date: 2023-03-25 13:54:09.316552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3620de4c5783'
down_revision = 'e43454b58e77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('league_members', schema=None) as batch_op:
        batch_op.drop_constraint('league_members_league_id_fkey', type_='foreignkey')
        batch_op.drop_column('league_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('league_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('league_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('league_members_league_id_fkey', 'league', ['league_id'], ['id'])

    # ### end Alembic commands ###
