"""add League_members id

Revision ID: 3b1bab763c5b
Revises: bd09e7b4e96c
Create Date: 2023-03-25 11:13:49.379072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b1bab763c5b'
down_revision = 'bd09e7b4e96c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('league_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('league_members', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###
