"""Add playing_now and upcoming_opponent to Football_Teams table

Revision ID: 41b26df8c840
Revises: f1b216bb9ef6
Create Date: 2023-04-15 12:40:59.281587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41b26df8c840'
down_revision = 'f1b216bb9ef6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('football__teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('playing_now', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('upcoming_opponent', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('football__teams', schema=None) as batch_op:
        batch_op.drop_column('upcoming_opponent')
        batch_op.drop_column('playing_now')

    # ### end Alembic commands ###
