"""add date_and_time_added to HistoryOfWaivers

Revision ID: 468c6d432edd
Revises: c87d45cf47a6
Create Date: 2023-10-28 10:20:02.075351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '468c6d432edd'
down_revision = 'c87d45cf47a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history_of_waivers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_and_time_added', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history_of_waivers', schema=None) as batch_op:
        batch_op.drop_column('date_and_time_added')

    # ### end Alembic commands ###
