"""create Player_weekly_info table, add draft_date to League table

Revision ID: 52c16985429a
Revises: 55905a8e4a92
Create Date: 2023-04-05 19:27:15.180549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52c16985429a'
down_revision = '55905a8e4a92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('league', schema=None) as batch_op:
        batch_op.add_column(sa.Column('draft_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('league', schema=None) as batch_op:
        batch_op.drop_column('draft_date')

    # ### end Alembic commands ###
