"""add draft_complete to League table

Revision ID: 55905a8e4a92
Revises: a60503450c36
Create Date: 2023-03-26 15:56:16.335399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55905a8e4a92'
down_revision = 'a60503450c36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('league', schema=None) as batch_op:
        batch_op.add_column(sa.Column('draft_complete', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('league', schema=None) as batch_op:
        batch_op.drop_column('draft_complete')

    # ### end Alembic commands ###
