"""add id to list_of_leagues

Revision ID: 58d856d8b95e
Revises: 86b55cea7c33
Create Date: 2023-03-25 13:30:13.704523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58d856d8b95e'
down_revision = '86b55cea7c33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('list_of_leagues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('list_of_leagues', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###
