"""rolling back to previous migration

Revision ID: 5a0e02fb7f6e
Revises: 79ab010b4573
Create Date: 2023-03-19 14:26:08.537176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a0e02fb7f6e'
down_revision = '79ab010b4573'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('league_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('member', sa.Integer(), nullable=True))
        batch_op.drop_constraint('league_members_member_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['member'], ['id'])
        batch_op.drop_column('member_id')

    with op.batch_alter_table('list_of_leagues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('league', sa.Integer(), nullable=True))
        batch_op.drop_constraint('list_of_leagues_league_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'league', ['league'], ['id'])
        batch_op.drop_column('league_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('list_of_leagues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('league_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('list_of_leagues_league_id_fkey', 'league', ['league_id'], ['id'])
        batch_op.drop_column('league')

    with op.batch_alter_table('league_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('member_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('league_members_member_id_fkey', 'user', ['member_id'], ['id'])
        batch_op.drop_column('member')

    # ### end Alembic commands ###
