"""Add matchups_already_generated to League table

Revision ID: 7850c593df6e
Revises: a13d9c148e94
Create Date: 2024-06-03 21:35:38.248777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7850c593df6e'
down_revision = 'a13d9c148e94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('league', schema=None) as batch_op:
        batch_op.add_column(sa.Column('matchups_already_generated', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('league', schema=None) as batch_op:
        batch_op.drop_column('matchups_already_generated')

    # ### end Alembic commands ###
