"""add '_id' to league_members and list_of_leagues dbs

Revision ID: 79ab010b4573
Revises: f3e3f309ed41
Create Date: 2023-03-19 14:21:20.831057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79ab010b4573'
down_revision = 'f3e3f309ed41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('league_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('member_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('league_members_member_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['member_id'], ['id'])
        batch_op.drop_column('member')

    with op.batch_alter_table('list_of_leagues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('league_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('list_of_leagues_league_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'league', ['league_id'], ['id'])
        batch_op.drop_column('league')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('list_of_leagues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('league', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('list_of_leagues_league_fkey', 'league', ['league'], ['id'])
        batch_op.drop_column('league_id')

    with op.batch_alter_table('league_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('member', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('league_members_member_fkey', 'user', ['member'], ['id'])
        batch_op.drop_column('member_id')

    # ### end Alembic commands ###
