"""add league_id back to league_members

Revision ID: 80827fffc3f3
Revises: 3620de4c5783
Create Date: 2023-03-25 13:54:39.088827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80827fffc3f3'
down_revision = '3620de4c5783'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('league_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('league_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'league', ['league_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('league_members', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('league_id')

    # ### end Alembic commands ###
