"""add relationship for league_members

Revision ID: 8d6ba9e9c98d
Revises: b263fbf09cd8
Create Date: 2023-03-19 10:00:52.715729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d6ba9e9c98d'
down_revision = 'b263fbf09cd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('league_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('member', sa.Integer(), nullable=True))
        batch_op.drop_constraint('league_members_list_of_members_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['member'], ['id'])
        batch_op.drop_column('list_of_members')

    with op.batch_alter_table('list_of_leagues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('league', sa.Integer(), nullable=True))
        batch_op.drop_constraint('list_of_leagues_list_of_leagues_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'league', ['league'], ['id'])
        batch_op.drop_column('list_of_leagues')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('list_of_leagues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('list_of_leagues', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('list_of_leagues_list_of_leagues_fkey', 'league', ['list_of_leagues'], ['id'])
        batch_op.drop_column('league')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('league_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('list_of_members', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('league_members_list_of_members_fkey', 'user', ['list_of_members'], ['id'])
        batch_op.drop_column('member')

    # ### end Alembic commands ###
