"""Change league_owner to league_manager

Revision ID: 8f45a30201e9
Revises: ad32c0f3bd75
Create Date: 2023-03-18 15:22:58.398239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f45a30201e9'
down_revision = 'ad32c0f3bd75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('league_members')
    op.drop_table('list_of_leagues')
    with op.batch_alter_table('league', schema=None) as batch_op:
        batch_op.add_column(sa.Column('league_manager', sa.Integer(), nullable=True))
        batch_op.drop_constraint('league_league_owner_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['league_manager'], ['id'])
        batch_op.drop_column('league_owner')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('league', schema=None) as batch_op:
        batch_op.add_column(sa.Column('league_owner', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('league_league_owner_fkey', 'user', ['league_owner'], ['id'])
        batch_op.drop_column('league_manager')

    op.create_table('list_of_leagues',
    sa.Column('user_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('list_of_leagues', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['list_of_leagues'], ['league.id'], name='list_of_leagues_list_of_leagues_fkey'),
    sa.PrimaryKeyConstraint('user_id', name='list_of_leagues_pkey')
    )
    op.create_table('league_members',
    sa.Column('league_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('list_of_members', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['list_of_members'], ['user.id'], name='league_members_list_of_members_fkey'),
    sa.PrimaryKeyConstraint('league_id', name='league_members_pkey')
    )
    # ### end Alembic commands ###
