"""Add priority to Waiver_Info table

Revision ID: 99c8148c9c73
Revises: 11106d4d5441
Create Date: 2023-04-30 20:21:15.249986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99c8148c9c73'
down_revision = '11106d4d5441'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waiver__info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waiver__info', schema=None) as batch_op:
        batch_op.drop_column('priority')

    # ### end Alembic commands ###
