"""add chance_to_win column to Football_Teams model

Revision ID: a13d9c148e94
Revises: 468c6d432edd
Create Date: 2023-11-11 11:33:45.030615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a13d9c148e94'
down_revision = '468c6d432edd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('football__teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chance_to_win', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('football__teams', schema=None) as batch_op:
        batch_op.drop_column('chance_to_win')

    # ### end Alembic commands ###
