"""Add date_added to Executed Waivers

Revision ID: a4046c9074a1
Revises: 32e023b1da7f
Create Date: 2023-07-21 14:05:32.185977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4046c9074a1'
down_revision = '32e023b1da7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('executed__waivers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_and_time_added', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('executed__waivers', schema=None) as batch_op:
        batch_op.drop_column('date_and_time_added')

    # ### end Alembic commands ###
