"""change league_members and list_of_leagues dbs

Revision ID: a60503450c36
Revises: d4b117972e7a
Create Date: 2023-03-25 14:36:03.906167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a60503450c36'
down_revision = 'd4b117972e7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('list_of_leagues')
    op.drop_table('league_members')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('league_members',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('league_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('member', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['league.id'], name='league_members_league_id_fkey'),
    sa.ForeignKeyConstraint(['member'], ['user.id'], name='league_members_member_fkey'),
    sa.PrimaryKeyConstraint('id', name='league_members_pkey')
    )
    op.create_table('list_of_leagues',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('league', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['league'], ['league.id'], name='list_of_leagues_league_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='list_of_leagues_user_id_fkey')
    )
    # ### end Alembic commands ###
