"""add relationship for list_of_leagues

Revision ID: b263fbf09cd8
Revises: 8f45a30201e9
Create Date: 2023-03-19 09:01:45.235636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b263fbf09cd8'
down_revision = '8f45a30201e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('league_members')
    with op.batch_alter_table('list_of_leagues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('list_of_leagues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.drop_column('id')

    op.create_table('league_members',
    sa.Column('league_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('list_of_members', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['list_of_members'], ['user.id'], name='league_members_list_of_members_fkey'),
    sa.PrimaryKeyConstraint('league_id', name='league_members_pkey')
    )
    # ### end Alembic commands ###
