"""add rankings to football teams table

Revision ID: b99f02befeb1
Revises: 7850c593df6e
Create Date: 2024-08-08 21:25:51.320854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b99f02befeb1'
down_revision = '7850c593df6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('football__teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ap_ranking', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('opponent_ap_ranking', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('football__teams', schema=None) as batch_op:
        batch_op.drop_column('opponent_ap_ranking')
        batch_op.drop_column('ap_ranking')

    # ### end Alembic commands ###
