"""upgrade again

Revision ID: c87d45cf47a6
Revises: 478af38a7fa6
Create Date: 2023-10-12 19:02:13.126429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c87d45cf47a6'
down_revision = '478af38a7fa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('football__teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('week0_opponent', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('week1_opponent', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('week2_opponent', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('week3_opponent', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('week4_opponent', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('week5_opponent', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('week6_opponent', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('week7_opponent', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('week8_opponent', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('week9_opponent', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('week10_opponent', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('week11_opponent', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('week12_opponent', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('week13_opponent', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('week14_opponent', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('week15_opponent', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('football__teams', schema=None) as batch_op:
        batch_op.drop_column('week15_opponent')
        batch_op.drop_column('week14_opponent')
        batch_op.drop_column('week13_opponent')
        batch_op.drop_column('week12_opponent')
        batch_op.drop_column('week11_opponent')
        batch_op.drop_column('week10_opponent')
        batch_op.drop_column('week9_opponent')
        batch_op.drop_column('week8_opponent')
        batch_op.drop_column('week7_opponent')
        batch_op.drop_column('week6_opponent')
        batch_op.drop_column('week5_opponent')
        batch_op.drop_column('week4_opponent')
        batch_op.drop_column('week3_opponent')
        batch_op.drop_column('week2_opponent')
        batch_op.drop_column('week1_opponent')
        batch_op.drop_column('week0_opponent')

    # ### end Alembic commands ###
