"""Change scores from floats to integers

Revision ID: d35f79b4bca6
Revises: f2be9a5d6849
Create Date: 2024-08-28 21:08:27.517003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd35f79b4bca6'
down_revision = 'f2be9a5d6849'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_weekly_info', schema=None) as batch_op:
        batch_op.alter_column('previous_weeks_score',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('this_weeks_score',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_weekly_info', schema=None) as batch_op:
        batch_op.alter_column('this_weeks_score',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('previous_weeks_score',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
