"""delete league_members

Revision ID: d4b117972e7a
Revises: 80827fffc3f3
Create Date: 2023-03-25 14:04:22.563890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4b117972e7a'
down_revision = '80827fffc3f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('league_members')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('league_members',
    sa.Column('member', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('league_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['league.id'], name='league_members_league_id_fkey'),
    sa.ForeignKeyConstraint(['member'], ['user.id'], name='league_members_member_fkey')
    )
    # ### end Alembic commands ###
