"""change to Executed Waivers update 1 table

Revision ID: e75e71408da3
Revises: a4046c9074a1
Create Date: 2023-07-21 14:27:04.111698

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e75e71408da3'
down_revision = 'a4046c9074a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('executed__waivers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('executed__waivers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('league', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('added_team', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dropped_team', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('faab_used', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date_and_time_added', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['league'], ['league.id'], name='executed__waivers_league_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='executed__waivers_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='executed__waivers_pkey')
    )
    # ### end Alembic commands ###
