"""redoing migrate

Revision ID: e7d323c5f2b2
Revises: e75e71408da3
Create Date: 2023-07-22 19:51:45.916149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7d323c5f2b2'
down_revision = 'e75e71408da3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('football__teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('previous_opponent', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('football__teams', schema=None) as batch_op:
        batch_op.drop_column('previous_opponent')

    # ### end Alembic commands ###
