"""Add updated_this_week to Football_Teams

Revision ID: f1b216bb9ef6
Revises: f573b43af687
Create Date: 2023-04-15 11:28:50.939364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1b216bb9ef6'
down_revision = 'f573b43af687'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('football__teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_this_week', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('football__teams', schema=None) as batch_op:
        batch_op.drop_column('updated_this_week')

    # ### end Alembic commands ###
