"""add total_wins row to Player_weekly_info

Revision ID: f2be9a5d6849
Revises: 1b29381764b2
Create Date: 2024-08-21 18:30:50.670756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2be9a5d6849'
down_revision = '1b29381764b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_weekly_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_wins', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_weekly_info', schema=None) as batch_op:
        batch_op.drop_column('total_wins')

    # ### end Alembic commands ###
