"""Remove ids from League_members and List_of_leagues, make league_id and user_id primary keys

Revision ID: f3e3f309ed41
Revises: 8d6ba9e9c98d
Create Date: 2023-03-19 10:15:56.769860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3e3f309ed41'
down_revision = '8d6ba9e9c98d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('league_members', schema=None) as batch_op:
        batch_op.alter_column('league_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('id')

    with op.batch_alter_table('list_of_leagues', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('list_of_leagues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('league_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.alter_column('league_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
