"""Add scores to Football_teams table

Revision ID: f573b43af687
Revises: ceb0aa57dbdc
Create Date: 2023-04-12 20:54:59.327308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f573b43af687'
down_revision = 'ceb0aa57dbdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('football__teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('week0_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('week1_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('week2_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('week3_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('week4_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('week5_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('week6_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('week7_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('week8_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('week9_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('week10_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('week11_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('week12_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('week13_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('week14_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('week15_score', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('football__teams', schema=None) as batch_op:
        batch_op.drop_column('week15_score')
        batch_op.drop_column('week14_score')
        batch_op.drop_column('week13_score')
        batch_op.drop_column('week12_score')
        batch_op.drop_column('week11_score')
        batch_op.drop_column('week10_score')
        batch_op.drop_column('week9_score')
        batch_op.drop_column('week8_score')
        batch_op.drop_column('week7_score')
        batch_op.drop_column('week6_score')
        batch_op.drop_column('week5_score')
        batch_op.drop_column('week4_score')
        batch_op.drop_column('week3_score')
        batch_op.drop_column('week2_score')
        batch_op.drop_column('week1_score')
        batch_op.drop_column('week0_score')

    # ### end Alembic commands ###
